<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBzzA8lk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBzzA8lk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBzzA8lk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBzzA8lk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBzzA8lk\App_KernelDevDebugContainer([
    'container.build_hash' => 'BzzA8lk',
    'container.build_id' => '952de4b1',
    'container.build_time' => 1608119073,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBzzA8lk');
