<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ45zbl2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ45zbl2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ45zbl2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ45zbl2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ45zbl2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q45zbl2',
    'container.build_id' => 'e67be683',
    'container.build_time' => 1610010417,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ45zbl2');
