<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTj0xgNK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTj0xgNK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTj0xgNK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTj0xgNK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTj0xgNK\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tj0xgNK',
    'container.build_id' => '9376bc40',
    'container.build_time' => 1610042961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTj0xgNK');
